# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

version: '3'

services:
  pfcon_dev:
    image:   ${CREPO}/pfstorage
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ./pfstorage/pfstorage.py:/usr/local/lib/python3.6/dist-packages/pfstorage/pfstorage.py
      # - .:/usr/local/lib/python3.5/dist-packages/pfcon
    ports:
      - "4005:4005"
    depends_on:
      - swift_service
    labels:
      name: "pfstorage"
      role: "PF storage, a module for interacting with openstorage backends."
    command: ["--verbosity", "1", "--debugToDir", "/tmp"]

  swift_service:
    image:   fnndsc/docker-swift-onlyone
    volumes:
      - swift_storage:/srv
    ports:
      - "8080:8080"
    labels:
      name: "swift"
      role: "swift object storage service"

volumes:
  swift_storage:
